
services:
  bntl-app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    command: ["poetry", "run", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "${PORT}"]
    depends_on:
      - mongodb
      - qdrant
    volumes:
      - .:/app
    
  vectorizer-app:
    build: .
    ports:
      - "${VECTORIZER_PORT}:${VECTORIZER_PORT}"
    command: ["poetry", "run", "uvicorn", "vectorizer.server:app", "--host", "0.0.0.0", "--port", "${VECTORIZER_PORT}", "--workers", "${VECTORIZER_WORKERS}"]
    depends_on:
      - mongodb
      - qdrant
    volumes:
      - .:/app

  mongodb:
    image: mongo:7
    ports: 
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./mongo-data:/data/db

  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
    volumes:
      - ./qdrant-data:/qdrant/storage

