#!/bin/bash
DIR=/home/ubuntu/bntl/
VENV=$DIR/.venv/bin/activate

# load .env
set -a && source $DIR/.env && set +a

cd $DIR
source $VENV

exec python -m vllm.entrypoints.openai.api_server --model ${VECTORIZER_MODEL} --port ${VECTORIZER_PORT}
